### ISSUE TITLE
What's the number of subchilds？

### ISSUE THREAD

**Issue by kaikai-sk** [thegedge/java-radix-tree#3]
As far as I know，the number of childnode in radix tree is 2^n.But I look this code,the number is not limited? Can you explain it??? ^_^

**Comment by thegedge** [comment]
Sorry for the delay, @kaikai-sk , but I was enjoying a vacation 🌴 🌞 

I'll get back to you asap, but it's been awhile looking at this code, so I don't know the answer off the top of my head.

**Comment by kaikai-sk** [comment]
I wanna wait for your answer . What's more,in linux kernel , the number of childnode in radix tree is 2^n

**Comment by thegedge** [comment]
Yeah, it definitely _looks_ like that could be the case, although I'd have to dig some more to see if that's _truly_ what happens. Specifically, it seems like this:

https://github.com/thegedge/radix-tree/blob/e20439a1fdedc9a93204c56beff4c48815912e10/src/main/java/ca/gedge/radixtree/RadixTree.java#L397-L415

could result in an arbitrary number of children.

Note that I actually based this code on another repository, and made a bunch of tweaks to clean up, simplify, and adhere to the `java.util.Map` interface. I didn't actually dig into the definition of a radix tree until now, so thanks for the query 😸
