### ISSUE TITLE
bug (parent not merge with the only remaining child)] after one of two children and low efficiency using getChildren().iterator()

### ISSUE THREAD

**Issue by galleChristian** [thegedge/java-radix-tree#4]
original code    `RadixTree.remove(String key, RadixTreeNode<V> node);`  parent need merge with the only remaining child

you may look at my implementation ( https://github.com/galleChristian/java-datastructure-radixtree/);

**Comment by thegedge** [comment]
Hey, @galleChristian! Thanks for the report. It's been a long time since I've been in the Java game though, so I should probably archive this repo to emphasize that.
